name: quiz_app
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0



flutter:

  uses-material-design: true
  assets:
    - images/istiaq.jpg
    - images/icon.png
    - images/biology.png
    - images/chemistry.png
    - images/gk.png
    - images/math.png
    - images/physics.png
    - images/programming.png


  fonts:
  - family: Pacifico
    fonts:
    - asset: fonts/Pacifico-Regular.ttf
  - family: SourceSansPro
    fonts:
    - asset: fonts/SourceSansPro-Regular.ttf     
  - family: Roboto
    fonts:
    - asset: fonts/Roboto-Regular.ttf     


